# Use official Python 3.11 image from Docker Hub
FROM python:3.11-slim

# Set environment variables
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app

# Set working directory
WORKDIR /app

# Copy project files for dependency installation
COPY pyproject.toml .
COPY README.md .
COPY LICENSE .

# Install dependencies from pyproject.toml
RUN pip install --upgrade pip && pip install -e .

# Copy the rest of application code
COPY nfl_predictor /app/nfl_predictor

# Run the app
CMD ["python", "nfl_predictor/nfl_ai_scores.py"]
